services:
  db:
    container_name: db
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=Hl7FudwaSNzOhhioo0GxlmmMD0LM+I8StQIqJCZ1TPg=
    ports:
      - 5432:5432
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  website:
    container_name: website
    image: website
    # image: ghcr.io/pratchaya-maneechot/sskru/website:v1.0.0-staging - Uncomment to use image from Github registry
  backend:
    container_name: backend
    image: api-gateway
    # image: ghcr.io/pratchaya-maneechot/sskru/api-gateway:v1.0.0-staging - Uncomment to use image from Github registry
    environment:
      - DB_PASSWORD=Hl7FudwaSNzOhhioo0GxlmmMD0LM+I8StQIqJCZ1TPg=
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PORT=5432
      - DB_SSL_REQUIRED=0
      - STORAGE_BUCKET_NAME=sskru-development.firebasestorage.app
      - APP_NAME=api-gateway
  proxy:
    container_name: proxy
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./infra/proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - website
      - backend
